# Generated by Django 5.1.2 on 2024-10-28 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_last_login_ip_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='ip_address',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
